### ISSUE TITLE
求CK怎么填写，我按照要求填写，本地node.js运行失败

### ISSUE THREAD

**Issue by qxy0789** [lxrcbw/JDDJ#1]
cookie只要里面的deviceid_pdj_jd=xxx-xxx-xxx;o2o_m_h5_sid=xxx-xxx-xxx关键信息，我按照这个填写，运行出现错误：SyntaxError: Invalid or unexpected token!

**Comment by lxrcbw** [comment]
看文件里的描述 浏览器抓包那个京东到家的网址 然后提取ck里的这部分 并前后添加"再放入那个cookie文件里
